#!/usr/bin/env bash

echo 'Installing Composer Dependencies'
composer require guzzlehttp/guzzle

echo 'Installing Composer Developer Dependencies'
composer require --dev \
    ahuggins/open-on-make \
    barryvdh/laravel-debugbar \
    beyondcode/laravel-self-diagnosis

echo 'Installing Linting and Styling Dependencies'
yarn add --dev eslint eslint-config-prettier eslint-config-prettier-standard \
    eslint-config-standard eslint-plugin-import eslint-plugin-node \
    eslint-plugin-prettier eslint-plugin-promise eslint-plugin-standard \
    eslint-plugin-vue prettier prettier-eslint prettier-standard 

echo '' >> $PROJECTPATH/.env
echo 'OPEN_ON_MAKE_EDITOR=code' >> $PROJECTPATH/.env
echo 'OPEN_ON_MAKE_ENABLED=true' >> $PROJECTPATH/.env
echo '' >> $PROJECTPATH/.env.example
echo 'OPEN_ON_MAKE_EDITOR=code' >> $PROJECTPATH/.env.example
echo 'OPEN_ON_MAKE_ENABLED=true' >> $PROJECTPATH/.env.example

echo 'Copying Include Files'
cp -R ~/.lambo/includes/ $PROJECTPATH

echo 'Adding Develpment Git Hook'
cp ~/.lambo/resources/hooks/post-merge-dev.sh $PROJECTPATH/.git/hooks/post-merge

echo 'Removing Twitter Bootstrap and Using Vue.js Only'
php artisan preset none && php artisan preset vue

echo 'Committing modifications to Git'
git add --all .
git commit -m 'Lambo after script.'